In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("NHL_dataF.csv")

In [3]:
data.head()

CF%  CF/60  CA/60    GF%  GF/60  GA/60   xGF%  xGF/60  xGA/60   Sh%  \
0  50.71  45.86  44.57  52.97   1.89   1.68  48.73    1.92    2.02  7.30   
1  50.96  50.37  48.47  52.73   2.39   2.14  51.10    2.22    2.13  8.40   
2  47.35  50.30  55.93  50.34   2.34   2.31  45.83    2.12    2.50  8.23   
3  44.35  47.09  59.08  46.53   2.09   2.40  44.08    1.92    2.43  7.87   
4  48.54  51.29  54.38  47.26   2.13   2.37  47.13    2.05    2.30  7.99   

     Sv%     PDO  SC  
0  93.62  100.93   0  
1  92.42  100.82   0  
2  92.75  100.98   0  
3  92.31  100.18   0  
4  91.66   99.65   0

In [4]:
array = data.values
X = array[:,0:12]
Y = array[:,12]

In [6]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

In [7]:
test = SelectKBest(score_func=chi2, k=4)
fit = test.fit(X, Y)

np.set_printoptions(precision=3)
print(fit.scores_)

features = fit.transform(X)
print(features[0:5,:])

[2.189 2.027 2.37  6.856 0.191 0.445 2.087 0.077 0.099 0.027 0.041 0.058]
[[50.71 44.57 52.97 48.73]
 [50.96 48.47 52.73 51.1 ]
 [47.35 55.93 50.34 45.83]
 [44.35 59.08 46.53 44.08]
 [48.54 54.38 47.26 47.13]]


In [8]:
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

In [9]:
model = LogisticRegression()
rfe = RFE(model, 4)
fit = rfe.fit(X, Y)
print("Num Features: %s" % (fit.n_features_))
print("Selected Features: %s" % (fit.support_))
print("Feature Ranking: %s" % (fit.ranking_))

Num Features: 4
Selected Features: [ True False False  True False False False False False  True False  True]
Feature Ranking: [1 3 2 1 8 4 5 9 6 1 7 1]


C:\Users\millerc4\AppData\Local\Continuum\anaconda2\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
