In [22]:
import pandas as pd
import numpy as np

In [23]:
data = pd.read_csv("NHL_data.csv")

In [24]:
data.head()

CF%  CF/60  CA/60    GF%  GF/60  GA/60   xGF%  xGF/60  xGA/60   Sh%  \
0  50.71  45.86  44.57  52.97   1.89   1.68  48.73    1.92    2.02  7.30   
1  50.96  50.37  48.47  52.73   2.39   2.14  51.10    2.22    2.13  8.40   
2  47.35  50.30  55.93  50.34   2.34   2.31  45.83    2.12    2.50  8.23   
3  44.35  47.09  59.08  46.53   2.09   2.40  44.08    1.92    2.43  7.87   
4  48.54  51.29  54.38  47.26   2.13   2.37  47.13    2.05    2.30  7.99   

     Sv%     PDO  Playoffs  
0  93.62  100.93         1  
1  92.42  100.82         1  
2  92.75  100.98         0  
3  92.31  100.18         1  
4  91.66   99.65         0

In [25]:
array = data.values
X = array[:,0:12]
Y = array[:,12]

In [26]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

In [27]:
test = SelectKBest(score_func=chi2, k=4)
fit = test.fit(X, Y)

np.set_printoptions(precision=3)
print(fit.scores_)

features = fit.transform(X)
print(features[0:5,:])

[10.554  9.378 13.404 63.005  2.013  3.959 18.825  0.769  0.938  1.998
  0.408  1.016]
[[50.71 44.57 52.97 48.73]
 [50.96 48.47 52.73 51.1 ]
 [47.35 55.93 50.34 45.83]
 [44.35 59.08 46.53 44.08]
 [48.54 54.38 47.26 47.13]]


In [28]:
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

In [29]:
model = LogisticRegression()
rfe = RFE(model, 4)
fit = rfe.fit(X, Y)
print("Num Features: %s" % (fit.n_features_))
print("Selected Features: %s" % (fit.support_))
print("Feature Ranking: %s" % (fit.ranking_))

Num Features: 4
Selected Features: [False False False  True  True  True False  True False False False False]
Feature Ranking: [8 6 7 1 1 1 4 1 3 5 9 2]


In [18]:
from sklearn.linear_model import Ridge

In [19]:
ridge = Ridge(alpha=1.0)
ridge.fit(X,Y)

Ridge(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=None,
   normalize=False, random_state=None, solver='auto', tol=0.001)

In [20]:
def pretty_print_coefs(coefs, names = None, sort = False):
    if names == None:
        names = ["X%s" % x for x in range(len(coefs))]
    lst = zip(coefs, names)
    if sort:
        lst = sorted(lst, key = lambda x:-np.abs(x[0]))
    return " + ".join("%s * %s" % (round(coef, 3), name) for coef, name in lst)

In [21]:
print("Ridge model:", pretty_print_coefs(ridge.coef_))

('Ridge model:', '0.038 * X0 + -0.032 * X1 + 0.027 * X2 + 0.084 * X3 + -0.037 * X4 + -0.179 * X5 + 0.018 * X6 + 0.213 * X7 + -0.04 * X8 + -0.026 * X9 + 0.003 * X10 + -0.055 * X11')
